# this file contains coco lexicon for concept dependency
lexicon ={'person': 'ACTOR',
                'bicycle': 'OBJECT',
                'car': 'OBJECT',
                'motorcycle': 'OBJECT',
                'airplane': 'OBJECT',
                'bus': 'OBJECT',
                'train': 'OBJECT',
                'truck': 'OBJECT',
                'boat': 'OBJECT',
                'traffic light': 'LOCATION',
                'fire hydrant': 'LOCATION',
                'stop sign': 'LOCATION',
                'parking meter': 'LOCATION',
                'bench': 'LOCATION',
                'bird': 'ACTOR',
                'cat': 'ACTOR',
                'dog': 'ACTOR',
                'horse': 'ACTOR',
                'sheep': 'ACTOR',
                'cow': 'ACTOR',
                'elephant': 'ACTOR',
                'bear': 'ACTOR',
                'zebra': 'ACTOR',
                'giraffe': 'ACTOR',
                'backpack': 'OBJECT',
                'umbrella': 'OBJECT',
                'handbag': 'OBJECT',
                'tie': 'OBJECT',
                'suitcase': 'OBJECT',
                'frisbee': 'OBJECT',
                'skis': 'OBJECT',
                'snowboard': 'OBJECT',
                'sports ball': 'OBJECT',
                'kite': 'OBJECT', 
                'baseball bat': 'OBJECT', 
                'baseball glove': 'OBJECT',
                'skateboard': 'OBJECT', 
                'surfboard': 'OBJECT', 
                'tennis racket': 'OBJECT',
                'bottle': 'OBJECT',
                'wine glass': 'OBJECT',
                'cup': 'OBJECT',
                'fork': 'OBJECT',
                'knife': 'OBJECT',
                'spoon': 'OBJECT',
                'bowl': 'OBJECT',
                'banana': 'OBJECT',
                'apple': 'OBJECT',
                'sandwich': 'OBJECT',
                'orange': 'OBJECT',
                'broccoli': 'OBJECT',
                'carrot': 'OBJECT',
                'hot dog': 'OBJECT',
                'pizza': 'OBJECT',
                'donut': 'donut',
                'cake': 'OBJECT',
                'chair': 'OBJECT',
                'couch': 'OBJECT',
                'potted plant': 'OBJECT',
                'bed': 'OBJECT',
                'dining table': 'OBJECT',
                'toilet': 'OBJECT',
                'tv': 'OBJECT',
                'laptop': 'OBJECT',
                'mouse': 'OBJECT',
                'remote': 'OBJECT',
                'keyboard': 'OBJECT',
                'cell phone': 'OBJECT',
                'microwave': 'OBJECT',
                'oven': 'OBJECT',
                'toaster': 'OBJECT',
                'sink': 'OBJECT',
                'refrigerator': 'OBJECT',
                'book': 'OBJECT',
                'clock': 'OBJECT',
                'vase': 'OBJECT',
                'scissors': 'OBJECT',
                'teddy bear': 'OBJECT',
                'hair drier': 'OBJECT',
                'toothbrush':'OBJECT'}

classes = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
